version: "3"

services:
  test-db:
    image: postgres 
    container_name: test-db
    networks:
      - main 
    environment:
      - POSTGRES_DB=main_test
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  app:
    build: .
    container_name: app
    environment:
      - DB_URL=postgres://postgres:postgres@test-db:5432/main_test?sslmode=disable
    depends_on:
      - test-db
    command: /opt/app/scripts/test.sh
    networks:
      - main 
networks:
  main:
    driver: bridge