// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	entities "xendit-takehome/github/entities"

	mock "github.com/stretchr/testify/mock"
)

// UserRepository is an autogenerated mock type for the UserRepository type
type UserRepository struct {
	mock.Mock
}

// GetUser provides a mock function with given fields: apiKey
func (_m *UserRepository) GetUser(apiKey string) (entities.UserOrganisation, error) {
	ret := _m.Called(apiKey)

	var r0 entities.UserOrganisation
	if rf, ok := ret.Get(0).(func(string) entities.UserOrganisation); ok {
		r0 = rf(apiKey)
	} else {
		r0 = ret.Get(0).(entities.UserOrganisation)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(apiKey)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
